//created on: Apr 7, 2014
package com.beans.leaveapp.drl
import com.beans.leaveapp.applyleave.model.ApprovalLevelModel


rule "Require Team Lead Approval" ruleflow-group "leaveapprovalrequirement"

    when
        $p: ApprovalLevelModel(role == "ROLE_EMPLOYEE")
    then
		modify($p) {
			setApprover("ROLE_TEAMLEAD");
		}
end

rule "Require Operation Director Approval" ruleflow-group "leaveapprovalrequirement"

    when
        $p: ApprovalLevelModel(role == "ROLE_TEAMLEAD" || role == "ROLE_HR")
    then
		modify($p) {
			setApprover("ROLE_OPERDIR");
		}
end